### ISSUE TITLE
Al iniciar sesión en cursame.es/es te envia a cursa.me

### ISSUE THREAD

**Issue by lruiz05** [cursame/issues#120]
Al iniciar sesión en cursame.es/es/login (con las credenciales de un usuario de España)
![captura de pantalla 2015-06-25 a las 11 31 40](https://cloud.githubusercontent.com/assets/7157588/8359818/60f4424c-1b2e-11e5-95ce-a2af5e71ff38.png)

Te cambia al dominio cursa.me

![captura de pantalla 2015-06-25 a las 11 32 13](https://cloud.githubusercontent.com/assets/7157588/8359878/c23cb2d2-1b2e-11e5-8d76-d3b9cffd65fd.png)

**Comment by alfredo777** [comment]
Se soluciona el issue mediante la inyección de un código de host en el js para validar hacia donde se dispara.

![captura de pantalla 2015-07-01 a las 20 52 04](https://cloud.githubusercontent.com/assets/677420/8468549/560b2792-2033-11e5-8300-7be5014ae15f.png)
![captura de pantalla 2015-07-01 a las 20 52 42](https://cloud.githubusercontent.com/assets/677420/8468550/56151504-2033-11e5-865d-f87594e4b247.png)
